class_name Sprites
extends RefCounted
## Loads the art in assets/ by name, so scenes never hard-code paths:
##
##   Sprites.species(&"owl")        the owl standing, facing down (16x16)
##   Sprites.sheet(&"owl")          assets/sprites/owl.png, its whole walk sheet
##   Sprites.walk_frames(&"player") a SpriteFrames for an AnimatedSprite2D
##   Sprites.portrait(&"owl")       assets/portraits/owl.png, 32x32
##   Sprites.tile("grass")          assets/tiles/grass.png
##
## A character's PNG is a walk sheet: rows face down, up, left, right;
## columns are stand, step, stand, step, stand. Frame 0 is the standing
## pose and frames 1-4 loop as the walk. That is the layout the overworld's
## SpriteBank (src/world/sprite_bank.gd, on the overworld branch) reads, so
## one file serves both; it cycles 1 + phase % (frames - 1), which is why
## the sheet ends on a stand: with four columns the walk would skip a stand
## every other step.
##
## Every loader returns null when the file is missing instead of erroring,
## so callers can keep their code-drawn placeholder as the fallback (the
## table and overworld were built before any art existed, and a species
## added to Species.CATALOG won't have art on day one). It checks
## ResourceLoader.exists() first because load() on a missing path logs an
## error, which the test runner counts as a failure.
##
## The PNGs are generated by tools/make_art.gd; assets/README.md has every
## file, its size and layout. Replacing a PNG with an Aseprite export of the
## same size and layout needs no code change here.

const SPRITE_DIR := "res://assets/sprites/"
const PORTRAIT_DIR := "res://assets/portraits/"
const TILE_DIR := "res://assets/tiles/"

## Walk-sheet rows, top to bottom. Columns are frames: 0 stands, 1-4 walk.
enum Facing { DOWN, UP, LEFT, RIGHT }
const WALK_FRAMES := 5
const FACING_NAMES := ["down", "up", "left", "right"]


## A species standing and facing the camera (16x16), cut from its sheet.
static func species(id: StringName) -> Texture2D:
	return character(id)


## Any character standing and facing down, by id: a species id, "player"
## (16x24), "npc" (a rival handler) or a townsperson ("npc_cook",
## "npc_kid", "npc_dealer", all 16x24; "npc_badger", 16x16).
static func character(id: StringName) -> Texture2D:
	return walk_frame(id, Facing.DOWN, 0)


## A character's whole walk sheet, or null.
static func sheet(id: StringName) -> Texture2D:
	return _load(SPRITE_DIR + "%s.png" % id)


static func player() -> Texture2D:
	return character(&"player")


static func npc() -> Texture2D:
	return character(&"npc")


## A species' 32x32 portrait, for the Binder and seat badges.
static func portrait(id: StringName) -> Texture2D:
	return _load(PORTRAIT_DIR + "%s.png" % id)


## A tile or facade by file name without extension: "grass", "path",
## "tree", "roof", "wall", "door", "floor", "counter", "diner"... See
## tile_names() for what exists and assets/README.md for what each is.
static func tile(tile_name: String) -> Texture2D:
	return _load(TILE_DIR + tile_name + ".png")


## The size of one walk frame: 16x16 for animals, 16x24 for people.
static func frame_size(id: StringName) -> Vector2i:
	var tex := sheet(id)
	if tex == null:
		return Vector2i.ZERO
	return Vector2i(tex.get_width() / WALK_FRAMES, tex.get_height() / FACING_NAMES.size())


## One frame of the walk sheet, or null.
static func walk_frame(id: StringName, facing: Facing, frame: int) -> AtlasTexture:
	var tex := sheet(id)
	if tex == null:
		return null
	var size := frame_size(id)
	var atlas := AtlasTexture.new()
	atlas.atlas = tex
	atlas.region = Rect2(Vector2(posmod(frame, WALK_FRAMES) * size.x, int(facing) * size.y), size)
	return atlas


## Animations for an AnimatedSprite2D: "walk_down", "walk_up",
## "walk_left", "walk_right" (frames 1-4, looping) and "idle_down"...
## (frame 0).
## "default" is idle_down, so a fresh AnimatedSprite2D shows something.
## Null when the character has no walk sheet.
static func walk_frames(id: StringName, fps := 6.0) -> SpriteFrames:
	if sheet(id) == null:
		return null
	var frames := SpriteFrames.new()
	for facing: int in Facing.values():
		var dir: String = FACING_NAMES[facing]
		frames.add_animation("walk_" + dir)
		frames.set_animation_speed("walk_" + dir, fps)
		frames.set_animation_loop("walk_" + dir, true)
		for i in range(1, WALK_FRAMES):
			frames.add_frame("walk_" + dir, walk_frame(id, facing, i))
		frames.add_animation("idle_" + dir)
		frames.add_frame("idle_" + dir, walk_frame(id, facing, 0))
	frames.add_frame("default", walk_frame(id, Facing.DOWN, 0))
	return frames


## Every tile name in assets/tiles/, sorted. Works in exported builds too,
## where the folder lists only the .import files.
static func tile_names() -> PackedStringArray:
	var names := PackedStringArray()
	for file in DirAccess.get_files_at(TILE_DIR):
		var base := file.trim_suffix(".import")
		if base.ends_with(".png") and not names.has(base.get_basename()):
			names.append(base.get_basename())
	names.sort()
	return names


static func _load(path: String) -> Texture2D:
	if not ResourceLoader.exists(path):
		return null
	return load(path) as Texture2D
